### ISSUE TITLE
Request failed with status code 504

### ISSUE THREAD

**Issue by Gajesh2007** [pi0neerpat/truffle-plugin-one-click-dapp#3]

**Comment by Gajesh2007** [comment]
@pi0neerpat @ejwessel Please help

**Comment by pi0neerpat** [comment]
Hey, sorry the main OCD server is down, will hopefully have it back up soon! Sorry for the inconvenience

**Comment by Gajesh2007** [comment]
When will it go up?

I am not perfect at the front end which makes my blockchain project incomplete

**Comment by pi0neerpat** [comment]
I just published v2 of https://oneclickdapp.com 

I don't have the API service running yet, so until then you'll have to make the new dapps manually, instead of via truffle

Will post here when the new service is up and it works with Truffle again

**Comment by Gajesh2007** [comment]
Great! Thank you! 😀
